trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_SUBSCRIPTION_ID: ed535055-bb61-47c6-b2f1-f1d702537e94

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: azdo-csekraken
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        set -euo pipefail

        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
        
        openssl pkcs12 -inkey $(Agent.TempDirectory)/spnCert.pem -in $(Agent.TempDirectory)/spnCert.pem -export -out $(Agent.TempDirectory)/spnCert.pfx -passout pass:
        echo "##vso[task.setvariable variable=ARM_CLIENT_CERTIFICATE_PATH]$(Agent.TempDirectory)/spnCert.pfx"

  - bash: TF_LOG=debug terraform init
    env:
      ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
