trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: azdo-csekraken
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        set -euo pipefail

        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
        
        openssl pkcs12 -inkey $(Agent.TempDirectory)/spnCert.pem -in $(Agent.TempDirectory)/spnCert.pem -export -out $(Agent.TempDirectory)/spnCert.pfx -passout pass:
        echo "##vso[task.setvariable variable=ARM_CLIENT_CERTIFICATE_PATH]$(Agent.TempDirectory)/spnCert.pfx"
        
        echo "##vso[task.setvariable variable=ARM_CLIENT_CERTIFICATE_PASSWORD]"

  - bash: TF_LOG=debug terraform init
