trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Snag the client cert and set up auth for Terraform
  # wow. https://discuss.hashicorp.com/t/azure-service-principal-client-certificate-error/32037?msclkid=9351d13bd12411ec96deb763dd60b7af
  - task: AzureCLI@2
    inputs:
      azureSubscription: azdo-csekraken
      scriptType: bash
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        set -euo pipefail

        echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
        echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"

        AZURE_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$AZURE_SUBSCRIPTION_ID"
        
        openssl pkcs12 -inkey $(Agent.TempDirectory)/spnCert.pem -in $(Agent.TempDirectory)/spnCert.pem -export -out $(Agent.TempDirectory)/spnCert.pfx -passout pass: -certpbe PBE-SHA1-3DES -keypbe PBE-SHA1-3DES -macalg sha1
        echo "##vso[task.setvariable variable=ARM_CLIENT_CERTIFICATE_PATH]$(Agent.TempDirectory)/spnCert.pfx"

  - bash: terraform init
  - bash: terraform plan
