trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: azdo-csekraken
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az group list -o table    

  - bash: |
      set -x
      
      ls -al $(Agent.TempDirectory)
      ls -al $(System.DefaultWorkingDirectory)
